# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yansayfalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yansayfalar',
            name='yanSayfaLink',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
